version: "3"

services:
  web-app-dev:
    container_name: web-app-dev
    build:
      context: ../../.
      dockerfile: docker/dev/Dockerfile
    # Set envrionment variables based on the .env file
    env_file:
      - ../../.env
    volumes:
      - ../../src:/app/src
      - ../../public:/app/public
    restart: always
    ports:
      - 3000:3000
    networks:
      - my_network

  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  my_network:
    external: true
